package guest

import (
	"fmt"
	"hash/fnv"
	"io"
	"log/slog"
	"net"
	"net/url"
	"os"
	"strings"
	"sync"

	"github.com/edwinavalos/onyx/internal/vsockproto"
	"github.com/mdlayher/vsock"
)

// GitConfigFile is included from the work user's ~/.gitconfig (baked into
// the image) and rewrites upstream URLs to the loopback proxies.
var GitConfigFile = "/run/onyx/gitconfig"

// hostCID is the vsock address of the host.
const hostCID = 2

var (
	proxyMu   sync.Mutex
	proxyURLs = map[string]string{} // upstream → loopback URL
)

// applyProxies starts a loopback listener per item, forwarding each
// accepted connection to the host's vsock port, then records the mapping
// for git and for the environment.
func applyProxies(items []vsockproto.ProxyItem) error {
	for _, it := range items {
		// The port is a stable function of the upstream so URLs git records
		// on a persistent volume keep working across boots.
		addr := fmt.Sprintf("127.0.0.1:%d", loopbackPort(it.Upstream))
		l, err := net.Listen("tcp", addr) //nolint:noctx // long-lived listener
		if err != nil {
			return fmt.Errorf("proxy %s: listen %s: %w", it.Name, addr, err)
		}
		local := "http://" + l.Addr().String()
		go bridge(l, it)
		proxyMu.Lock()
		proxyURLs[it.Upstream] = local
		proxyMu.Unlock()

		u, err := url.Parse(it.Upstream)
		if err == nil {
			envMu.Lock()
			envMap["ONYX_PROXY_"+envName(u.Host)] = local
			envMap["ONYX_PROXY_"+envName(u.Host)+"_AUTH"] = it.Auth
			envMu.Unlock()
		}
		slog.Info("guest: proxy bridged", "name", it.Name, "upstream", it.Upstream, "local", local)
	}
	if err := writeGitConfig(); err != nil {
		return err
	}
	envMu.Lock()
	defer envMu.Unlock()
	return writeEnvFile()
}

func bridge(l net.Listener, it vsockproto.ProxyItem) {
	for {
		c, err := l.Accept()
		if err != nil {
			return
		}
		go func() {
			defer c.Close()
			h, err := vsock.Dial(hostCID, it.HostPort, nil)
			if err != nil {
				slog.Warn("guest: proxy dial host", "name", it.Name, "err", err)
				return
			}
			defer func() { _ = h.Close() }()
			done := make(chan struct{}, 2)
			go func() { _, _ = io.Copy(h, c); _ = h.Close(); done <- struct{}{} }()
			go func() { _, _ = io.Copy(c, h); _ = c.Close(); done <- struct{}{} }()
			<-done
		}()
	}
}

func writeGitConfig() error {
	proxyMu.Lock()
	defer proxyMu.Unlock()
	var b strings.Builder
	b.WriteString("# Generated by onyx-guest: git talks to host-side credential proxies.\n")
	for upstream, local := range proxyURLs {
		fmt.Fprintf(&b, "[url \"%s/\"]\n\tinsteadOf = %s/\n", local, strings.TrimSuffix(upstream, "/"))
	}
	return os.WriteFile(GitConfigFile, []byte(b.String()), 0o644) // #nosec G306 -- read by the work user's git
}

// loopbackPort maps an upstream origin to a port in 40000–49999.
func loopbackPort(upstream string) int {
	h := fnv.New32a()
	_, _ = h.Write([]byte(strings.TrimSuffix(strings.ToLower(upstream), "/")))
	return 40000 + int(h.Sum32()%10000)
}

func envName(host string) string {
	var b strings.Builder
	for _, r := range strings.ToUpper(host) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}
